### PR TITLE
security: remove insecure and unused clean-css dependency

### PR DESCRIPTION
**Pull request by shanebonham**
ref: https://github.com/jakubpawlowicz/clean-css/commit/2929bafbf8cdf7dccb24e0949c70833764fa87e3

### CODE REVIEW

**Comment by chantastic** [comment]
thank you, sir 🎩

**Comment by shanebonham** [comment]
Sorry to interrupt your vacation. Would you be able to publish a new release?

**Comment by chantastic** [comment]
not at all. a hazard of linking a personal project.

i don't have a computer with me but i can add you as a maintainer to my npm
packages.
what's your user?

**Comment by shanebonham** [comment]
`shanebonham`

If you want to wait, that's fine too. We have it working with the fork in `ministrycentered`.

**Comment by chantastic** [comment]
you should have write access to my projects now.

if you have the app secured with a fork, and this proves inconvenient, i'm
happy to re-publish and PR a version update into people upon my return.

**Comment by chantastic** [comment]
strange that i wasn't notified of the security warning via email or
nofication

**Comment by chantastic** [comment]
`npm publish` will take care of this package. don't worry about publishing the nested packages because no code changed

**Comment by shanebonham** [comment]
OK, done! Thanks. You might still want to update the version in the repo to `0.3.2`.

**Comment by chantastic** [comment]
🔥
thanks! will do

**Pull request merged**
