### PR TITLE
Fix print media query

### PR DESCRIPTION
**Pull request by jonsuh**
Should the print media queries not include `screen and` so the media query is just `@media print`? https://github.com/chantastic/minions.css/pull/43/commits/a9ea2108a2d5a699fa58604a5673b9aab85d46c1

### CODE REVIEW

**Comment by chantastic** [comment]
curious. i'd swear i did this at one point. so bizzare.

thanks!

**Comment by chantastic** [comment]
@jonsuh mind rebasing this off the updated master? i'm not able to easily do it on your fork.

thanks!

**Comment by jonsuh** [comment]
@chantastic Rebased. No need to worry about this today & this weekend—this can definitely wait till Monday.

**Comment by chantastic** [comment]
@jonsuh thanks! updated and all packages republished at `0.3.0`

**Pull request merged**
